export enum Callback {
  STOKE_WIDTH_CHANGE,
  STROKE_COLOR_CHANGE,
  FILL_COLOR_CHANGE,
  FONT_SIZE_CHANGE,
  FONT_COLOR_CHANGE,
  FONT_BACKGROUND_CHANGE,

  SELECT_TOOl_ON,
  SELECT_TOOl_OFF,
  EDIT_TOOl_ON,
  EDIT_TOOl_OFF,
  ANGLE_CHANGE,
  REF_POINT_CHANGE,
  FOCUS_CHANGED,
  BLURED
}
